server:
  port: ${AUTHENTICATION_SERVICE:8084}
spring:
  application:
    name: Authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/wave27
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl:auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true